server:
  port: 8080
  servlet:
    application-display-name: 博客后端管理

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: crystal
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

    # 配置模版引擎
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML 5
      cache: false

    mvc:
        static-path-pattern: /**


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  config-location: classpath:mybatis/mybatis-config.xml

#自定义的属性，指定了一个路径，注意要以/结尾
blog.imagesPath: D:/images/
logging:
  config: classpath:log4j2.xml

#表示所有的访问都经过静态资源路径
spring.mvc.static-path-pattern: /**

#覆盖默认配置，所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径
#在最末尾的file:${web.upload-path}中的file:表示是一个具体的硬盘路径，其他的使用classpath指的是系统环境变量
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${blog.imagesPath}