server:
  port: 8080
  servlet:
    application-display-name: 博客后端管理

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: crystal
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    mode: HTML 5
    cache: false


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  config-location: classpath:mybatis/mybatis-config.xml