server:
  port: 8081
  servlet:
    application-display-name: 博客后端管理

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/blog
    url: jdbc:mysql://crystalcao.top:3306/blog?useUnicode=true&amp;characterEncoding=utf-8
    username: crystal
    #password: 123456
    password: Crystal@123
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  # 配置模版引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML 5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8

  mvc:
    static-path-pattern: /**

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  config-location: classpath:mybatis/mybatis-config.xml

#自定义的属性，指定了一个路径，注意要以/结尾
blog.common.imagesPath: /tmp/blog/images/
logging:
  config: classpath:log4j2.xml

#表示所有的访问都经过静态资源路径
spring.mvc.static-path-pattern: /**

#覆盖默认配置，所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径
#在最末尾的file:${blog.imagesPath}中的file:表示是一个具体的硬盘路径，其他的使用classpath指的是系统环境变量
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${blog.imagesPath}

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 登陆的一些配置
login:
  wechat:
    # appid: wx639c64d4a47ce07b
    # appsecret: 6207967674ab338a68d738e9232c023e
    appid: wx16c38049de96f3a3
    appsecret: 6922006a4c58ef075aeb1a6742cc66bc
    redirectUrl: gh_76ede78aa807
    token: crystalwechat
  qq:
    appid: wx639c64d4a47ce07b
    appsecret: 6207967674ab338a68d738e9232c023e
    redirectUrl: gh_76ede78aa807
